"""Diff and patch utility for token-efficient targeted text polishing.

Applies SEARCH/REPLACE blocks generated by LLMs to existing draft translations,
avoiding the need to regenerate full chapters for minor edits.
"""
import logging
import re
from typing import Tuple

logger = logging.getLogger(__name__)

SEARCH_REPLACE_PATTERN = re.compile(
    r"<<<<<<<\s*SEARCH\s*\r?\n(.*?)\r?\n=======\s*\r?\n(.*?)\r?\n>>>>>>>",
    re.DOTALL
)


def is_patch_format(text: str) -> bool:
    """Check if the given text contains at least one SEARCH/REPLACE block or NO_CHANGES_NEEDED signal."""
    if not text:
        return False
    return "NO_CHANGES_NEEDED" in text or bool(SEARCH_REPLACE_PATTERN.search(text))


def apply_search_replace_patches(
    original_text: str,
    patch_text: str
) -> Tuple[str, int, int]:
    """Apply <<<<<<< SEARCH ... ======= ... >>>>>>> diff blocks to original_text.

    Args:
        original_text: The base document text to be modified.
        patch_text: String containing one or more SEARCH/REPLACE blocks.

    Returns:
        Tuple of (modified_text, applied_count, failed_count).
    """
    if not patch_text or not original_text:
        return original_text, 0, 0

    if "NO_CHANGES_NEEDED" in patch_text:
        return original_text, 0, 0

    matches = list(SEARCH_REPLACE_PATTERN.finditer(patch_text))
    if not matches:
        return original_text, 0, 0

    current_text = original_text
    applied = 0
    failed = 0

    for match in matches:
        search_block = match.group(1)
        replace_block = match.group(2)

        # 1. Exact string match
        if search_block in current_text:
            current_text = current_text.replace(search_block, replace_block, 1)
            applied += 1
            continue

        # 2. Stripped boundary match (common LLM trailing space variance)
        stripped_search = search_block.strip()
        if stripped_search and stripped_search in current_text:
            current_text = current_text.replace(stripped_search, replace_block.strip(), 1)
            applied += 1
            continue

        # 3. Line-by-line whitespace-tolerant match
        search_lines = [line.strip() for line in search_block.splitlines() if line.strip()]
        if not search_lines:
            failed += 1
            continue

        orig_lines = current_text.splitlines()
        found_idx = -1
        search_len = len(search_lines)

        for i in range(len(orig_lines) - search_len + 1):
            window = [orig_lines[i + j].strip() for j in range(search_len)]
            if window == search_lines:
                found_idx = i
                break

        if found_idx >= 0:
            before_lines = orig_lines[:found_idx]
            after_lines = orig_lines[found_idx + search_len:]
            replacement_lines = replace_block.splitlines()
            current_text = "\n".join(before_lines + replacement_lines + after_lines)
            applied += 1
        else:
            logger.debug(f"Failed to find search block in text: {search_block[:80]!r}...")
            failed += 1

    return current_text, applied, failed
