"""Prompts package."""
from src.prompts.templates import (
    CHRONICLER_SYSTEM_PROMPT,
    CRITIQUE_SYSTEM_PROMPT,
    DRAFTING_SYSTEM_PROMPT,
    EXTRACTION_SYSTEM_PROMPT,
    POLISHING_SYSTEM_PROMPT,
)

__all__ = [
    "EXTRACTION_SYSTEM_PROMPT",
    "DRAFTING_SYSTEM_PROMPT",
    "CRITIQUE_SYSTEM_PROMPT",
    "POLISHING_SYSTEM_PROMPT",
    "CHRONICLER_SYSTEM_PROMPT",
]
